[tool.kedro]
package_name = "nlp_with_disaster_feeds"
project_name = "nlp-with-disaster-feeds"
project_version = "0.17.5"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/nlp_with_disaster_feeds -ra"""
