[tool.kedro]
package_name = "sentiment_analysis_twitter"
project_name = "Sentiment Analysis Twitter"
project_version = "0.18.4"

[tool.isort]
profile = "black"
known_third_party = ["kedro", "pandas", "pytest", "sklearn", "spacy", "tqdm"]


[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.coverage.paths]
source = ["src"]
test = ["tests"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["*/__init__.py"]

