########### Data Preprocessing ##########
spellcheck: False
lemmatization: True

########## Feature Engineering ##########
test_size: 0.33
vectorizer:
  =: sklearn.feature_extraction.text.TfidfVectorizer
  analyzer: 'word'
  stop_words: 'english'

########## Train Eval ##########
model:
  =: sklearn.naive_bayes.MultinomialNB
  alpha: 1
